#!/bin/bash

DIR=$HOME/Pictures/wallpapers
PICS=($(ls ${DIR}))

RANDOMPICS=${PICS[ $RANDOM % ${#PICS[@]} ]}

awww img ${DIR}/${RANDOMPICS} -t wipe --transition-step 180 --transition-duration 1.0 --transition-angle 135
notify-send "${RANDOMPICS}"
